name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-beta*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: oxiqr

jobs:
  checks:
    uses: ./.github/workflows/rust-checks.yaml

  release:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release --locked

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cp target/release/$BINARY_NAME dist/${BINARY_NAME}-${{ runner.os }}-${{ runner.arch }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          make_latest: ${{ !contains(github.ref_name, '-beta') }}
